### PR TITLE
Host on Cevi.Tools Cluster

### PR DESCRIPTION
**Pull request by wp99cp**
This PR includes the necessary changes to host the application on our Cevi.Tools cluster

## Open Todos
- [ ] CeviDB Login
- [x] Icons
- [x] Mail Verification
- [ ] Check every functionality
- [x] Persistent DB, on shared storage
- [x] phpMyAdmin as dashboard for MySQL database

### CODE REVIEW

**Comment by jeromesigg** [comment]
Icons: URL added to Font-Awesome Kit

**Comment by wp99cp** [comment]
This is the solution to the mail verification problem: https://stackoverflow.com/a/73215178/13371311

The root of the problem is that our Laravel applications run behind a reverse proxy. However this raises a new problem, if you run the containers locally, we have no a problem with mixed HTTPS and HTTP requests.

**Comment by jeromesigg** [comment]
Check every functionality: 

x Login / Registration
x New user
x New comment
x Change qualification
x New survey
x Upload file on comment
- Show file on comment: File is not showing
x Show printable version
- Close Survey: Problem with second survey (not related to hosting changes)
- Admin Login: Password not known

**Comment by wp99cp** [comment]
> * [ ]  Show file on comment: File is not showing

Yes, that's correct. For the new hosting, I've split the PHP processor (PHP FPM) and the web hosting (nginx), see https://blog.devsense.com/2019/php-nginx-docker. The file get uploaded correctly and are saved inside the PHP processor container. However, they are not exposed to the nginx web server.

Does the application create any other local files? Are any directories that must be persistent across reboots of the docker container? What is the `storage` directory? Are there any files saved that cannot be restored automatically after reboot?

**Comment by wp99cp** [comment]
> > * [ ]   Show file on comment: File is not showing
> 
> Yes, that's correct. For the new hosting, I've split the PHP processor (PHP FPM) and the web hosting (nginx), see https://blog.devsense.com/2019/php-nginx-docker. The file get uploaded correctly and are saved inside the PHP processor container. However, they are not exposed to the nginx web server.
> 
> Does the application create any other local files? Are any directories that must be persistent across reboots of the docker container? What is the `storage` directory? Are there any files saved that cannot be restored automatically after reboot?

**Comment by jeromesigg** [comment]
> * [ ]  Show file on comment: File is not showing

All files uploaded (avatar if not from Cevi-DB, files from posts) are stored in the `images/{camp_name}/` folder, with this it is possible to delete the folder once the camp is finished.
No files from the users are stored in the `storage` directory and also in the `upload` directory (old directory)

**Review by wp99cp — COMMENTED** [review]
I've updated the missing parts. The production environment should now be ready.

**Pull request merged**
